/*
 * This file was automatically generated by EvoSuite
 * Sun Sep 03 04:14:23 GMT 2023
 */

package com.accionlabs.evodemo.db;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ConnectionUtil_ESTest extends ConnectionUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        ConnectionUtil.getInstance();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class com.accionlabs.db.ConnectionUtil$ConnectionUtilInstance
         //
         verifyException("com.accionlabs.db.ConnectionUtil", e);
      }
  }
}
